(1, 'For tis the sport to have the engineer hoist with his own petard...', 'William Shakespeare')
(2, 'As flies to wanton boys, are we to the gods, they kill us for their sport.', 'William Shakespeare')
(3, 'Amazing things do happen in sport sometimes, obviously, Rogers a massive, massive favorite going into the match. I would expect him to win fairly comfortably.', 'Andy Murray')
(4, 'He is a role model for every Austrian tennis player. He is the biggest in our sport in Austria, that is why, even though I am a little bit too young for him, he is still a role model for everyone.', 'Dominic Thiem')
(5, 'In politics, absurdity is not a handicap.', 'Napoleon Bonaparte')
(6, 'In politics the middle way is none at all.', 'John Adams')
(7, 'The climate is not going to collapse because some party got the most votes. The politics that is needed to prevent the climate catastrophe—it does not exist today. We need to change the system, as if we were in crisis, as if there were a war going on.', 'Greta Thunberg')
(8, 'It is one of those new challenges in our modern society that crosses the old divides - transcends politics, transcends ideology.', 'Barack Obama')
(9, 'Yes, we have to divide up our time like that, between our politics and our equations. But to me our equations are far more important, for politics are only a matter of present concern. A mathematical equation stands forever.', 'Albert Einstein')
(10, 'If you cannot love yourself how in the hell are you gonna love somebody else?', 'RuPaul')
(11, 'When you become the image of your own imagination, it is the most powerful thing you could ever do.', 'RuPaul')
(12, 'We were all born naked and the rest is drag.', 'RuPaul')
(13, 'Not today Satan! Not today!', 'Bianca Del Rio')
(14, 'History is philosophy teaching by example, and also warning its two eyes are geography and chronology.', 'James A. Garfield')
(15, 'I hate Mondays.', 'Garfield')
(16, 'I love lasagna.', 'Garfield')
(17, 'I have developed a new philosophy... I only dread one day at a time.', 'Charlie Brown')
(18, 'Music is a higher revelation than philosophy.', 'Ludwig van Beethoven')
(19, 'This is my simple religion. There is no need for temples no need for complicated philosophy. Our own brain, our own heart is our temple the philosophy is kindness.', 'Dalai Lama')
(20, 'Philosophy is to the real world as masturbation is to sex.', 'Karl Marx')
(21, 'Philosophy is the science which considers truth.', 'Aristotle')
(22, 'I have gained this by philosophy that I do without being commanded what others do only from fear of the law.', 'Aristotle')
(23, 'There are more things in heaven and earth, Horatio,Than are dreamt of in your philosophy.', 'William Shakespeare')
(24, 'Accidents will occur in the best-regulated families; and in families not regulated by that pervading influence which sanctifies while it enhances... in short, by the influence of Woman, in the lofty character of Wife, they may be expected with confidence, and must be borne with philosophy.', 'Charles Dickens')
(25, 'Education is what remains after one has forgotten everything one learned in school.', 'Albert Einstein')
(26, 'Free speech carries with it some freedom to listen.', 'Bob Marley')
(27, 'I am selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you cannot handle me at my worst, then you sure as hell do not deserve me at my best.', 'Marilyn Monroe')
(28, 'Be yourself; everyone else is already taken.', 'Oscar Wilde')
(29, 'Two things are infinite: the universe and human stupidity; and I am not sure about the universe.', 'Albert Einstein')
(30, 'So many books, so little time.', 'Frank Zappa')
(31, 'You know you are in love when you cannot fall asleep because reality is finally better than your dreams.', 'Dr. Seuss')
(32, 'You only live once, but if you do it right, once is enough.', 'Mae West')
(33, 'Be the change that you wish to see in the world.', 'Mahatma Gandhi')
(34, 'If you tell the truth, you do not have to remember anything.', 'Mark Twain')
(35, 'I have learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.', 'Maya Angelou')
(36, 'Always forgive your enemies; nothing annoys them so much.', 'Oscar Wilde')
(37, 'To live is the rarest thing in the world. Most people exist, that is all.', 'Oscar Wilde')
(38, 'Live as if you were to die tomorrow. Learn as if you were to live forever.', 'Mahatma Gandhi')
(39, 'Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.', 'Martin Luther King Jr.')
(40, 'Without music, life would be a mistake.', 'Friedrich Nietzsche')
(41, 'All that is gold does not glitter,\r\nNot all those who wander are lost;\r\nThe old that is strong does not wither,\r\nDeep roots are not reached by the frost.\r\n\r\nFrom the ashes a fire shall be woken,\r\nA light from the shadows shall spring;\r\nRenewed shall be blade that was broken,\r\nThe crownless again shall be king.', 'J.R.R. Tolkien')
(42, 'Imperfection is beauty, madness is genius and it is better to be absolutely ridiculous than absolutely boring.', 'Marilyn Monroe')
(43, 'I have not failed. I have just found 10,000 ways that will not work.', 'Thomas A. Edison')
(44, 'I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.', 'Dr. Seuss')
(45, 'Love all, trust a few, do wrong to none.', 'William Shakespeare')
(46, 'A day without sunshine is like, you know, night.', 'Steve Martin')
(47, 'Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.', 'Lao Tzu')
(48, 'There is no greater agony than bearing an untold story inside you.', 'Maya Angelou')
(49, 'Everything you can imagine is real.', 'Pablo Picasso')
(50, 'Folks are usually about as happy as they make their minds up to be.', 'Abraham Lincoln')
(51, 'The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.', 'Bob Marley')
(52, 'Do what you can, with what you have, where you are.', 'Theodore Roosevelt')
(53, 'You may say I am a dreamer, but I am not the only one. I hope someday you will join us. And the world will live as one.', 'John Lennon')
(54, 'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.', 'Jane Austen')
(55, 'I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book! -- When I have a house of my own, I shall be miserable if I have not an excellent library.', 'Jimi Hendrix')
(56, 'Books are a uniquely portable magic.', 'Stephen King')
(57, '... a mind needs books as a sword needs a whetstone, if it is to keep its edge.', 'George R.R. Martin')
(58, 'Movies are like an expensive form of therapy for me.', 'Tim Burton')
(59, 'I do not always know what I want, but I do know what I do not want.', 'Stanley Kubrick')
(60, 'I am sure anyone who likes a good crime, provided it is not the victim.', 'Alfred Hitchcock')
(61, 'The only true wisdom is in knowing you know nothing.', 'Socrates')
(62, 'I became insane, with long intervals of horrible sanity.', 'Edgar Allan Poe')
(63, 'A Census Taker Once Tried To Test Me. I Ate His Liver With Some Fava Beans And A Nice Chianti.', 'Hanibal Lecter')
(64, 'It is Alive! It is Alive!', 'Dr. Frankenstein')
(65, 'Game Over.', 'Jigsaw/John Kramer')
(66, 'Why are you screaming? I have not even caught you yet.', 'Freddy Krueger')
(67, 'Here is Johnny!', 'Jack Torrance')
(68, 'Do not criticize what you cannot understand.', 'Bob Dylan')
(69, 'Take my hand and we will make it - I swear', 'Bon Jovi')
(70, 'Lose your dream, you lose your mind.', 'The Rolling Stones')
(71, 'I look forward to having a lunch with you again.', 'Twenty One Pilots')
(72, 'No matter gay, straight, or bi,\r\nLesbian, transgendered life,\r\nI am on the right track baby,\r\nI was born to survive.\r\nNo matter black, white or beige\r\nChola or orient made,\r\nI am on the right track baby,\r\nI was born to be brave.', 'Lady Gaga')
(73, 'Is this the real life?\r\nIs this just fantasy?', 'Queen')
(74, 'Believe It!', 'Naruto Uzomaki')
(75, 'It is Over 9000!', 'Vegeta')
(76, 'Only I Can Call My Dream Stupid!', 'Roronoa Zoro')
(77, 'Pikachu!', 'Pikachu')
(78, 'Let us Get to the Numbers!', 'James A. Janisse')
(79, 'Say hello to my little friend!', 'Tony Montana')
(80, 'I made my family disappear.', 'Kevin McCallister')
(81, 'I used to be an adventurer like you, then I took an arrow in the knee.', 'Whiterun Guard')
(82, 'Khajiit has wares, if you have coin.', 'Khajiit')
(83, 'Ohana means family. Family means nobody gets left behind or forgotten.', 'Stitch')
(84, 'Let us get down to business; to defeat the Huns.', 'Shang')
(85, 'Oh yes, the past can hurt. But, you can either run from it or, learn from it.', 'Rafiki')
(86, 'Hakuna matata!', 'Timon/Pumbaa')
(87, 'Once You have Met Someone You Never Really Forget Them. It Just Takes A While For Your Memories To Return.', 'Zeniba')
(88, 'Let it go!', 'Elsa')
(89, 'Look at this stuff, is it not neat?', 'Ariel, the little mermaid')
(90, 'Hello!', 'Mrs. Doubtfire')
(91, 'Groovy.', 'Ashley J. Williams')
(92, 'All I Want For Christmas Is You', 'Mariah Carey')
(93, 'Shagadelic baby!', 'Austin Powers')
(94, 'D-oh!', 'Homer J. Simpson')
(95, 'I am so smart; s-m-r-t!', 'Homer J. Simpson')
(96, 'It\'is great to be here. It\'s great to be anywhere.', 'Keith Richards')
(97, 'I got a jar of dirt, I got a jar of dirt, and guess what is inside it?', 'Jack Sparrow')
(98, 'No, i am your father.', 'Darth Vader/Anakin Skywalker')
(99, 'Können sie mich hören?', 'jeder Professor im Onlinemeeting')
(100, 'It is a me, Mario!', 'Mario Mario')